# Generated by Django 6.1.1 on 2026-09-26 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_name', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField()),
                ('assignment_date', models.DateTimeField(auto_now_add=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.base')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.equipmenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('expenditure_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.base')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.equipmenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.base')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.equipmenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.equipmenttype')),
                ('from_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='assets.base')),
                ('to_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='assets.base')),
            ],
        ),
    ]
